language: go
go:
 - 1.3.x
 - 1.4.x
 - 1.5.x
 - 1.6.x
 - 1.7.x
install:
  - go get github.com/flosch/pongo2
  - go get github.com/gorilla/mux
  - go get gopkg.in/yaml.v2

branches:
  only:
    - master

script:
  - go build main.go

